---
title: "InitialExploration"
author: "Celina"
date: "2/21/2022"
output: html_document
---

# Load in Packages and Data
```{r, include = FALSE}
library(readr)
library(tidyverse)
library(dplyr)
library(ggplot2)
data <- read_csv("Alzheimer_s_Disease_and_Healthy_Aging_Data.csv") %>%
  select(-c(RowId, 
            Response, 
            Data_Value_Alt, 
            ResponseID, 
            StratificationCategoryID3,
            Stratification3, 
            StratificationID3, 
            StratificationCategory3,
            Report, 
            Geolocation, 
            ClassID, 
            TopicID, 
            Data_Value_Unit, 
            DataValueTypeID, 
            Data_Value_Footnote_Symbol, 
            Sample_Size, 
            Data_Value_Footnote, 
            StratificationCategoryID1, StratificationID1, StratificationCategory1, 
            LocationAbbr, Datasource, 
            QuestionID, LocationID
            )) %>%
  drop_na(Data_Value) %>%
  pivot_wider(names_from = StratificationCategory2, values_from = Stratification2, values_fill = "Overall") %>%
  select(-c(StratificationCategoryID2, StratificationID2, Overall)) %>%
  rename(Age_Group = Stratification1, Race_Ethnicity = `Race/Ethnicity`)
```

```{r}
summary(data)

# Age_Group, Gender, Race_Ethnicity
data %>% 
  filter(Gender != "Overall") %>% 
  ggplot() + 
  geom_bar(aes(Gender))

data %>%
  filter(Age_Group != "Overall") %>%
  ggplot() + 
  geom_bar(aes(Age_Group))

data %>%
  filter(Race_Ethnicity != "Overall") %>% 
  ggplot() + 
  geom_bar(aes(Race_Ethnicity, fill=Race_Ethnicity))

data %>% 
  ggplot() + 
  geom_bar(aes(y = (LocationDesc)))

ggplot(data ) + 
  geom_bar(aes(Class))
```

```{r}
data
```

